// Seed data for Shop Floor Tracker.
// Bump SEED_DATA.version whenever the shape/content below changes so
// storage.js knows to re-seed localStorage instead of using stale data.

const SEED_DATA = {
  version: 2,

  WORKSTATIONS: [
    { id: "WS-A92", label: "A-92" },
    { id: "WS-B14", label: "B-14" },
    { id: "WS-C03", label: "C-03" },
  ],

  OPERATORS: [
    { id: "OP-001", name: "M. SMITH" },
    { id: "OP-002", name: "J. RIVERA" },
    { id: "OP-003", name: "A. CHEN" },
  ],

  PARTS: [
    { id: "PT-FUELLINE", name: "Fuel Line" },
    { id: "PT-NUTPLATE", name: "Nut Plates" },
    { id: "PT-ENGMOUNT", name: "Engine Mounts" },
    { id: "PT-BLASTSHIELD", name: "Blast Shields" },
    { id: "PT-WASHER", name: "Washers" },
    { id: "PT-VAPORTUBE", name: "Vaporizing Tube" },
    { id: "PT-NAS14N", name: "NAS-14N (Screw)" },
    { id: "PT-NAS15N", name: "NAS-15N (Screw)" },
    { id: "PT-SPAR", name: "Wing Spar" },
    { id: "PT-SKIN", name: "Skin Panel" },
    { id: "PT-RIVET", name: "Rivets" },
    { id: "PT-HINGE", name: "Control Surface Hinge" },
    { id: "PT-SEALANT", name: "Sealant Tube" },
    { id: "PT-INSPECTTAG", name: "Inspection Tag" },
  ],

  SEGMENTS: [
    { id: "SEG-WING", name: "Wing Assembly" },
    { id: "SEG-POWER", name: "Power System" },
    { id: "SEG-TAIL", name: "Tail Assembly" },
    { id: "SEG-PAYLOAD", name: "Payload Assembly" },
    { id: "SEG-ENGINE", name: "Engine Assembly" },
    { id: "SEG-LAUNCH", name: "Launch Interface" },
  ],

  JOBS: [
    {
      id: "JOB-001",
      name: "Engine Build — Unit 14",
      workOrderNo: "WO-4471",
      productName: "BARRACUDA-250 Engine Assembly",
      operatorId: "OP-001",
      workstationId: "WS-A92",
      order: 1,
    },
    {
      id: "JOB-002",
      name: "Engine Rebuild — Unit 15",
      workOrderNo: "WO-4472",
      productName: "BARRACUDA-250 Engine Assembly",
      operatorId: "OP-001",
      workstationId: "WS-A92",
      order: 2,
    },
    {
      id: "JOB-003",
      name: "Wing Build — Ship 7",
      workOrderNo: "WO-5108",
      productName: "BARRACUDA-250 Wing Set",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      order: 1,
    },
    {
      id: "JOB-004",
      name: "Wing Build — Ship 8",
      workOrderNo: "WO-5109",
      productName: "BARRACUDA-250 Wing Set",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      order: 2,
    },
    {
      id: "JOB-005",
      name: "Payload Bay Fit-Out — Unit 3",
      workOrderNo: "WO-6203",
      productName: "BARRACUDA-250 Payload Module",
      operatorId: "OP-003",
      workstationId: "WS-C03",
      order: 1,
    },
    {
      id: "JOB-006",
      name: "Launch Interface QA — Unit 3",
      workOrderNo: "WO-6204",
      productName: "BARRACUDA-250 Payload Module",
      operatorId: "OP-003",
      workstationId: "WS-C03",
      order: 2,
    },
  ],

  OPERATIONS: [
    // --- JOB-001 Engine Build — Unit 14 (OP-001 / WS-A92) ---
    {
      id: "TASK-001",
      jobId: "JOB-001",
      operatorId: "OP-001",
      workstationId: "WS-A92",
      segmentId: "SEG-ENGINE",
      opNumber: "01",
      name: "Engine ASSY",
      category: "Parts Retrieval",
      description: "Retrieve and stage all engine assembly parts at the workstation.",
      targetSeconds: 420,
      order: 1,
      modelType: "crate",
      parts: [
        { partId: "PT-ENGMOUNT", qty: 1 },
        { partId: "PT-NAS14N", qty: 1 },
      ],
    },
    {
      id: "TASK-002",
      jobId: "JOB-001",
      operatorId: "OP-001",
      workstationId: "WS-A92",
      segmentId: "SEG-ENGINE",
      opNumber: "02",
      name: "Fixture Setup",
      category: "Frame Prep",
      description: "Set up the assembly fixture and align the frame for engine mounting.",
      targetSeconds: 420,
      order: 2,
      modelType: "housing-block",
      parts: [
        { partId: "PT-WASHER", qty: 4 },
        { partId: "PT-NAS15N", qty: 2 },
      ],
    },
    {
      id: "TASK-003",
      jobId: "JOB-001",
      operatorId: "OP-001",
      workstationId: "WS-A92",
      segmentId: "SEG-ENGINE",
      opNumber: "03",
      name: "Mount Install",
      category: "Assembly",
      description: "Install engine mounts and torque to spec.",
      targetSeconds: 420,
      order: 3,
      modelType: "bracket",
      parts: [
        { partId: "PT-ENGMOUNT", qty: 2 },
        { partId: "PT-BLASTSHIELD", qty: 1 },
      ],
    },
    {
      id: "TASK-004",
      jobId: "JOB-001",
      operatorId: "OP-001",
      workstationId: "WS-A92",
      segmentId: "SEG-POWER",
      opNumber: "04",
      name: "Motor Wiring",
      category: "Electrical",
      description: "Route and connect motor wiring harness, secure with clips.",
      targetSeconds: 420,
      order: 4,
      modelType: "tube-assembly",
      parts: [
        { partId: "PT-FUELLINE", qty: 1 },
        { partId: "PT-VAPORTUBE", qty: 1 },
      ],
    },
    {
      id: "TASK-005",
      jobId: "JOB-001",
      operatorId: "OP-001",
      workstationId: "WS-A92",
      segmentId: "SEG-ENGINE",
      opNumber: "05",
      name: "Alignment Check",
      category: "Quality",
      description: "Verify engine alignment against jig tolerances and log readings.",
      targetSeconds: 300,
      order: 5,
      modelType: "flat-tag",
      parts: [{ partId: "PT-INSPECTTAG", qty: 1 }],
    },
    {
      id: "TASK-006",
      jobId: "JOB-001",
      operatorId: "OP-001",
      workstationId: "WS-A92",
      segmentId: "SEG-LAUNCH",
      opNumber: "06",
      name: "Final Inspection",
      category: "Quality",
      description: "Perform final visual and torque-stripe inspection before sign-off.",
      targetSeconds: 300,
      order: 6,
      modelType: "flat-tag",
      parts: [{ partId: "PT-INSPECTTAG", qty: 1 }],
    },

    // --- JOB-002 Engine Rebuild — Unit 15 (OP-001 / WS-A92) ---
    {
      id: "TASK-201",
      jobId: "JOB-002",
      operatorId: "OP-001",
      workstationId: "WS-A92",
      segmentId: "SEG-ENGINE",
      opNumber: "01",
      name: "Teardown & Inspect",
      category: "Disassembly",
      description: "Remove existing engine components and inspect for wear or damage.",
      targetSeconds: 360,
      order: 1,
      modelType: "housing-block",
      parts: [{ partId: "PT-INSPECTTAG", qty: 1 }],
    },
    {
      id: "TASK-202",
      jobId: "JOB-002",
      operatorId: "OP-001",
      workstationId: "WS-A92",
      segmentId: "SEG-ENGINE",
      opNumber: "02",
      name: "Mount Replace",
      category: "Assembly",
      description: "Install replacement engine mounts and torque to spec.",
      targetSeconds: 420,
      order: 2,
      modelType: "bracket",
      parts: [
        { partId: "PT-ENGMOUNT", qty: 2 },
        { partId: "PT-NAS14N", qty: 2 },
      ],
    },
    {
      id: "TASK-203",
      jobId: "JOB-002",
      operatorId: "OP-001",
      workstationId: "WS-A92",
      segmentId: "SEG-POWER",
      opNumber: "03",
      name: "Wiring Re-terminate",
      category: "Electrical",
      description: "Re-terminate motor wiring harness connections and secure routing.",
      targetSeconds: 420,
      order: 3,
      modelType: "tube-assembly",
      parts: [
        { partId: "PT-FUELLINE", qty: 1 },
        { partId: "PT-VAPORTUBE", qty: 1 },
      ],
    },
    {
      id: "TASK-204",
      jobId: "JOB-002",
      operatorId: "OP-001",
      workstationId: "WS-A92",
      segmentId: "SEG-LAUNCH",
      opNumber: "04",
      name: "Final Inspection",
      category: "Quality",
      description: "Perform final visual and torque-stripe inspection before sign-off.",
      targetSeconds: 300,
      order: 4,
      modelType: "flat-tag",
      parts: [{ partId: "PT-INSPECTTAG", qty: 1 }],
    },

    // --- JOB-003 Wing Build — Ship 7 (OP-002 / WS-B14) ---
    {
      id: "TASK-101",
      jobId: "JOB-003",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      segmentId: "SEG-WING",
      opNumber: "01",
      name: "Spar Prep",
      category: "Parts Retrieval",
      description: "Retrieve wing spar and inspect for shipping damage before staging.",
      targetSeconds: 360,
      order: 1,
      modelType: "crate",
      parts: [{ partId: "PT-SPAR", qty: 1 }],
    },
    {
      id: "TASK-102",
      jobId: "JOB-003",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      segmentId: "SEG-WING",
      opNumber: "02",
      name: "Skin Fitting",
      category: "Assembly",
      description: "Fit skin panels to the spar and clamp in position.",
      targetSeconds: 480,
      order: 2,
      modelType: "panel",
      parts: [
        { partId: "PT-SKIN", qty: 2 },
        { partId: "PT-SEALANT", qty: 1 },
      ],
    },
    {
      id: "TASK-103",
      jobId: "JOB-003",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      segmentId: "SEG-WING",
      opNumber: "03",
      name: "Rivet Install",
      category: "Assembly",
      description: "Drill and set rivets along the skin-to-spar seam per pattern.",
      targetSeconds: 600,
      order: 3,
      modelType: "fastener-array",
      parts: [{ partId: "PT-RIVET", qty: 24 }],
    },
    {
      id: "TASK-104",
      jobId: "JOB-003",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      segmentId: "SEG-TAIL",
      opNumber: "04",
      name: "Control Surface",
      category: "Assembly",
      description: "Install control surface hinges and check freedom of movement.",
      targetSeconds: 420,
      order: 4,
      modelType: "hinge-assembly",
      parts: [
        { partId: "PT-HINGE", qty: 2 },
        { partId: "PT-NAS14N", qty: 4 },
      ],
    },
    {
      id: "TASK-105",
      jobId: "JOB-003",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      segmentId: "SEG-WING",
      opNumber: "05",
      name: "Paint Prep",
      category: "Finishing",
      description: "Mask fasteners and clean surfaces in preparation for paint.",
      targetSeconds: 300,
      order: 5,
      modelType: "panel",
      parts: [{ partId: "PT-SEALANT", qty: 1 }],
    },
    {
      id: "TASK-106",
      jobId: "JOB-003",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      segmentId: "SEG-WING",
      opNumber: "06",
      name: "QA Check",
      category: "Quality",
      description: "Complete quality checklist and tag the assembly for hand-off.",
      targetSeconds: 300,
      order: 6,
      modelType: "flat-tag",
      parts: [{ partId: "PT-INSPECTTAG", qty: 1 }],
    },

    // --- JOB-004 Wing Build — Ship 8 (OP-002 / WS-B14) ---
    {
      id: "TASK-301",
      jobId: "JOB-004",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      segmentId: "SEG-WING",
      opNumber: "01",
      name: "Spar Prep",
      category: "Parts Retrieval",
      description: "Retrieve wing spar and inspect for shipping damage before staging.",
      targetSeconds: 360,
      order: 1,
      modelType: "crate",
      parts: [{ partId: "PT-SPAR", qty: 1 }],
    },
    {
      id: "TASK-302",
      jobId: "JOB-004",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      segmentId: "SEG-WING",
      opNumber: "02",
      name: "Skin Fitting",
      category: "Assembly",
      description: "Fit skin panels to the spar and clamp in position.",
      targetSeconds: 480,
      order: 2,
      modelType: "panel",
      parts: [
        { partId: "PT-SKIN", qty: 2 },
        { partId: "PT-SEALANT", qty: 1 },
      ],
    },
    {
      id: "TASK-303",
      jobId: "JOB-004",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      segmentId: "SEG-WING",
      opNumber: "03",
      name: "Rivet Install",
      category: "Assembly",
      description: "Drill and set rivets along the skin-to-spar seam per pattern.",
      targetSeconds: 600,
      order: 3,
      modelType: "fastener-array",
      parts: [{ partId: "PT-RIVET", qty: 24 }],
    },
    {
      id: "TASK-304",
      jobId: "JOB-004",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      segmentId: "SEG-TAIL",
      opNumber: "04",
      name: "Control Surface",
      category: "Assembly",
      description: "Install control surface hinges and check freedom of movement.",
      targetSeconds: 420,
      order: 4,
      modelType: "hinge-assembly",
      parts: [
        { partId: "PT-HINGE", qty: 2 },
        { partId: "PT-NAS14N", qty: 4 },
      ],
    },
    {
      id: "TASK-305",
      jobId: "JOB-004",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      segmentId: "SEG-WING",
      opNumber: "05",
      name: "QA Check",
      category: "Quality",
      description: "Complete quality checklist and tag the assembly for hand-off.",
      targetSeconds: 300,
      order: 5,
      modelType: "flat-tag",
      parts: [{ partId: "PT-INSPECTTAG", qty: 1 }],
    },

    // --- JOB-005 Payload Bay Fit-Out — Unit 3 (OP-003 / WS-C03) ---
    {
      id: "TASK-401",
      jobId: "JOB-005",
      operatorId: "OP-003",
      workstationId: "WS-C03",
      segmentId: "SEG-PAYLOAD",
      opNumber: "01",
      name: "Bay Prep",
      category: "Parts Retrieval",
      description: "Clear and stage the payload bay for fit-out.",
      targetSeconds: 360,
      order: 1,
      modelType: "crate",
      parts: [{ partId: "PT-NAS15N", qty: 4 }],
    },
    {
      id: "TASK-402",
      jobId: "JOB-005",
      operatorId: "OP-003",
      workstationId: "WS-C03",
      segmentId: "SEG-PAYLOAD",
      opNumber: "02",
      name: "Bracket Install",
      category: "Assembly",
      description: "Install mounting brackets and secure with washers per spec.",
      targetSeconds: 420,
      order: 2,
      modelType: "bracket",
      parts: [
        { partId: "PT-ENGMOUNT", qty: 1 },
        { partId: "PT-WASHER", qty: 4 },
      ],
    },
    {
      id: "TASK-403",
      jobId: "JOB-005",
      operatorId: "OP-003",
      workstationId: "WS-C03",
      segmentId: "SEG-PAYLOAD",
      opNumber: "03",
      name: "Seal & Inspect",
      category: "Quality",
      description: "Apply sealant and complete final inspection of the payload bay.",
      targetSeconds: 300,
      order: 3,
      modelType: "flat-tag",
      parts: [
        { partId: "PT-SEALANT", qty: 1 },
        { partId: "PT-INSPECTTAG", qty: 1 },
      ],
    },

    // --- JOB-006 Launch Interface QA — Unit 3 (OP-003 / WS-C03) ---
    {
      id: "TASK-501",
      jobId: "JOB-006",
      operatorId: "OP-003",
      workstationId: "WS-C03",
      segmentId: "SEG-LAUNCH",
      opNumber: "01",
      name: "Interface Torque Check",
      category: "Quality",
      description: "Verify torque on all launch interface fasteners against spec.",
      targetSeconds: 300,
      order: 1,
      modelType: "fastener-array",
      parts: [{ partId: "PT-NAS14N", qty: 6 }],
    },
    {
      id: "TASK-502",
      jobId: "JOB-006",
      operatorId: "OP-003",
      workstationId: "WS-C03",
      segmentId: "SEG-LAUNCH",
      opNumber: "02",
      name: "Umbilical Fit Check",
      category: "Assembly",
      description: "Confirm umbilical connector fit and line routing clearance.",
      targetSeconds: 420,
      order: 2,
      modelType: "tube-assembly",
      parts: [
        { partId: "PT-VAPORTUBE", qty: 1 },
        { partId: "PT-FUELLINE", qty: 1 },
      ],
    },
    {
      id: "TASK-503",
      jobId: "JOB-006",
      operatorId: "OP-003",
      workstationId: "WS-C03",
      segmentId: "SEG-LAUNCH",
      opNumber: "03",
      name: "Final Sign-off",
      category: "Quality",
      description: "Complete final QA checklist and tag the interface for hand-off.",
      targetSeconds: 240,
      order: 3,
      modelType: "flat-tag",
      parts: [{ partId: "PT-INSPECTTAG", qty: 1 }],
    },
  ],
};
