// Seed data for Shop Floor Tracker.
// Bump SEED_DATA.version whenever the shape/content below changes so
// storage.js knows to re-seed localStorage instead of using stale data.

const SEED_DATA = {
  version: 1,

  WORKSTATIONS: [
    { id: "WS-A92", label: "A-92" },
    { id: "WS-B14", label: "B-14" },
    { id: "WS-C03", label: "C-03" },
  ],

  OPERATORS: [
    { id: "OP-001", name: "M. SMITH" },
    { id: "OP-002", name: "J. RIVERA" },
    { id: "OP-003", name: "A. CHEN" },
  ],

  PARTS: [
    { id: "PT-FUELLINE", name: "Fuel Line" },
    { id: "PT-NUTPLATE", name: "Nut Plates" },
    { id: "PT-ENGMOUNT", name: "Engine Mounts" },
    { id: "PT-BLASTSHIELD", name: "Blast Shields" },
    { id: "PT-WASHER", name: "Washers" },
    { id: "PT-VAPORTUBE", name: "Vaporizing Tube" },
    { id: "PT-NAS14N", name: "NAS-14N (Screw)" },
    { id: "PT-NAS15N", name: "NAS-15N (Screw)" },
    { id: "PT-SPAR", name: "Wing Spar" },
    { id: "PT-SKIN", name: "Skin Panel" },
    { id: "PT-RIVET", name: "Rivets" },
    { id: "PT-HINGE", name: "Control Surface Hinge" },
    { id: "PT-SEALANT", name: "Sealant Tube" },
    { id: "PT-INSPECTTAG", name: "Inspection Tag" },
  ],

  SEGMENTS: [
    { id: "SEG-WING", name: "Wing Assembly" },
    { id: "SEG-POWER", name: "Power System" },
    { id: "SEG-TAIL", name: "Tail Assembly" },
    { id: "SEG-PAYLOAD", name: "Payload Assembly" },
    { id: "SEG-ENGINE", name: "Engine Assembly" },
    { id: "SEG-LAUNCH", name: "Launch Interface" },
  ],

  TASKS: [
    // --- OP-001 / M. SMITH / WS-A92 / BARRACUDA-250 engine build ---
    {
      id: "TASK-001",
      operatorId: "OP-001",
      workstationId: "WS-A92",
      segmentId: "SEG-ENGINE",
      opNumber: "01",
      name: "Engine ASSY",
      category: "Parts Retrieval",
      description: "Retrieve and stage all engine assembly parts at the workstation.",
      targetSeconds: 420,
      order: 1,
      parts: [
        { partId: "PT-ENGMOUNT", qty: 1 },
        { partId: "PT-NAS14N", qty: 1 },
      ],
    },
    {
      id: "TASK-002",
      operatorId: "OP-001",
      workstationId: "WS-A92",
      segmentId: "SEG-ENGINE",
      opNumber: "02",
      name: "Fixture Setup",
      category: "Frame Prep",
      description: "Set up the assembly fixture and align the frame for engine mounting.",
      targetSeconds: 420,
      order: 2,
      parts: [
        { partId: "PT-WASHER", qty: 4 },
        { partId: "PT-NAS15N", qty: 2 },
      ],
    },
    {
      id: "TASK-003",
      operatorId: "OP-001",
      workstationId: "WS-A92",
      segmentId: "SEG-ENGINE",
      opNumber: "03",
      name: "Mount Install",
      category: "Assembly",
      description: "Install engine mounts and torque to spec.",
      targetSeconds: 420,
      order: 3,
      parts: [
        { partId: "PT-ENGMOUNT", qty: 2 },
        { partId: "PT-BLASTSHIELD", qty: 1 },
      ],
    },
    {
      id: "TASK-004",
      operatorId: "OP-001",
      workstationId: "WS-A92",
      segmentId: "SEG-POWER",
      opNumber: "04",
      name: "Motor Wiring",
      category: "Electrical",
      description: "Route and connect motor wiring harness, secure with clips.",
      targetSeconds: 420,
      order: 4,
      parts: [
        { partId: "PT-FUELLINE", qty: 1 },
        { partId: "PT-VAPORTUBE", qty: 1 },
      ],
    },
    {
      id: "TASK-005",
      operatorId: "OP-001",
      workstationId: "WS-A92",
      segmentId: "SEG-ENGINE",
      opNumber: "05",
      name: "Alignment Check",
      category: "Quality",
      description: "Verify engine alignment against jig tolerances and log readings.",
      targetSeconds: 300,
      order: 5,
      parts: [{ partId: "PT-INSPECTTAG", qty: 1 }],
    },
    {
      id: "TASK-006",
      operatorId: "OP-001",
      workstationId: "WS-A92",
      segmentId: "SEG-LAUNCH",
      opNumber: "06",
      name: "Final Inspection",
      category: "Quality",
      description: "Perform final visual and torque-stripe inspection before sign-off.",
      targetSeconds: 300,
      order: 6,
      parts: [{ partId: "PT-INSPECTTAG", qty: 1 }],
    },

    // --- OP-002 / J. RIVERA / WS-B14 / Wing assembly build ---
    {
      id: "TASK-101",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      segmentId: "SEG-WING",
      opNumber: "01",
      name: "Spar Prep",
      category: "Parts Retrieval",
      description: "Retrieve wing spar and inspect for shipping damage before staging.",
      targetSeconds: 360,
      order: 1,
      parts: [{ partId: "PT-SPAR", qty: 1 }],
    },
    {
      id: "TASK-102",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      segmentId: "SEG-WING",
      opNumber: "02",
      name: "Skin Fitting",
      category: "Assembly",
      description: "Fit skin panels to the spar and clamp in position.",
      targetSeconds: 480,
      order: 2,
      parts: [
        { partId: "PT-SKIN", qty: 2 },
        { partId: "PT-SEALANT", qty: 1 },
      ],
    },
    {
      id: "TASK-103",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      segmentId: "SEG-WING",
      opNumber: "03",
      name: "Rivet Install",
      category: "Assembly",
      description: "Drill and set rivets along the skin-to-spar seam per pattern.",
      targetSeconds: 600,
      order: 3,
      parts: [{ partId: "PT-RIVET", qty: 24 }],
    },
    {
      id: "TASK-104",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      segmentId: "SEG-TAIL",
      opNumber: "04",
      name: "Control Surface",
      category: "Assembly",
      description: "Install control surface hinges and check freedom of movement.",
      targetSeconds: 420,
      order: 4,
      parts: [
        { partId: "PT-HINGE", qty: 2 },
        { partId: "PT-NAS14N", qty: 4 },
      ],
    },
    {
      id: "TASK-105",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      segmentId: "SEG-WING",
      opNumber: "05",
      name: "Paint Prep",
      category: "Finishing",
      description: "Mask fasteners and clean surfaces in preparation for paint.",
      targetSeconds: 300,
      order: 5,
      parts: [{ partId: "PT-SEALANT", qty: 1 }],
    },
    {
      id: "TASK-106",
      operatorId: "OP-002",
      workstationId: "WS-B14",
      segmentId: "SEG-WING",
      opNumber: "06",
      name: "QA Check",
      category: "Quality",
      description: "Complete quality checklist and tag the assembly for hand-off.",
      targetSeconds: 300,
      order: 6,
      parts: [{ partId: "PT-INSPECTTAG", qty: 1 }],
    },
  ],
};
